In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
merchant_names = [

'Amazon',
'Walmart',
'Target',
'Starbucks',
'Shell',
'Costco',
'Best Buy',
'Hilton',
'Marriott',
'Delta',
'United',
'Uber',
'Netflix',
'Apple',
'CVS'

]


categories = [

'Shopping',
'Dining',
'Travel',
'Fuel',
'Healthcare',
'Electronics',
'Entertainment',
'Hotels',
'Airlines',
'Groceries'

]


countries = [

'USA',
'Canada',
'UK',
'Australia',
'Singapore'

]

In [3]:
n_merchants = 5000


merchant_df = pd.DataFrame({

'merchant_id':[f'M{i:05}' for i in range(1,n_merchants+1)],


'merchant_name':

np.random.choice(
merchant_names,
n_merchants
),


'category':

np.random.choice(
categories,
n_merchants
),



'country':

np.random.choice(
countries,
n_merchants
),



'risk_score':

np.round(

np.random.uniform(
0,
1,
n_merchants
),

2

)

})



merchant_df.head()

  merchant_id merchant_name     category    country  risk_score
0      M00001         Delta    Groceries         UK        0.20
1      M00002          Uber  Electronics        USA        0.31
2      M00003         Shell     Airlines  Australia        0.62
3      M00004     Starbucks         Fuel     Canada        0.01
4      M00005         Delta   Healthcare     Canada        0.13

In [4]:
merchant_df.to_csv(

'../data/merchant_master.csv',

index=False

)

In [5]:
customers = pd.read_csv(

'../data/BankChurners.csv'

)



customer_ids = customers['CLIENTNUM']

In [6]:
engagement = pd.DataFrame({


'customer_id':customer_ids,


'app_logins':

np.random.randint(

0,
100,
len(customer_ids)

),



'email_clicks':

np.random.randint(

0,
50,
len(customer_ids)

),



'support_calls':

np.random.randint(

0,
10,
len(customer_ids)

),




'complaints':

np.random.randint(

0,
5,
len(customer_ids)

),




'offer_acceptance':

np.random.choice(

[0,1],

len(customer_ids)

)

})



engagement.head()

,customer_id,app_logins,email_clicks,support_calls,complaints,offer_acceptance
0,768805383,34,12,1,2,0
1,818770008,17,9,9,1,1
2,713982108,86,24,5,4,0
3,769911858,85,13,9,0,1
4,709106358,58,11,0,3,0

In [7]:
engagement.to_csv(

'../data/engagement.csv',

index=False

)