In [1]:
import pandas as pd
import numpy as np

In [3]:
retail = pd.read_csv(
    "../data/processed/retail_clean.csv"
)

customer360 = pd.read_csv(
    "../data/customer360.csv"
)

In [4]:
retail.head()

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [5]:
retail.columns

Index(['invoice', 'stockcode', 'description', 'quantity', 'invoicedate',
       'price', 'customer_id', 'country'],
      dtype='str')

In [6]:
retail['sales']=retail['quantity']*retail['price']

In [7]:
retail_features = retail.groupby(

'customer_id'

).agg(

frequency=('invoice','nunique'),

monetary=('sales','sum'),

avg_order_value=('sales','mean')

).reset_index()

In [8]:
retail_features.head()

   customer_id  frequency  monetary  avg_order_value
0      12346.0         15    -64.68        -1.406087
1      12347.0          2   1323.32        18.638310
2      12348.0          1    222.16        11.108000
3      12349.0          4   2646.99        24.738224
4      12351.0          1    300.93        14.330000

In [9]:
customer360 = customer360.merge(

retail_features,

on='customer_id',

how='left'

)

In [10]:
customer360.fillna(0,inplace=True)

,customer_id,age,gender,credit_limit,total_spend,transaction_count,utilization,churn_flag,engagement_score,offer_acceptance,frequency,monetary,avg_order_value
0,768805383,45,M,12691.0,1144,42,0.061,Existing Customer,7.2,0,0.0,0.0,0.0
1,818770008,49,F,8256.0,1291,33,0.105,Existing Customer,24.5,1,0.0,0.0,0.0
2,713982108,51,M,3418.0,1887,20,0.000,Existing Customer,21.6,0,0.0,0.0,0.0
3,769911858,40,F,3313.0,1171,20,0.760,Existing Customer,57.9,1,0.0,0.0,0.0
4,709106358,40,M,4716.0,816,28,0.000,Existing Customer,11.5,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,50,M,4003.0,15476,117,0.462,Existing Customer,28.0,1,0.0,0.0,0.0
10123,710638233,41,M,4277.0,8764,69,0.511,Attrited Customer,13.8,0,0.0,0.0,0.0
10124,716506083,44,F,5409.0,10291,60,0.000,Attrited Customer,31.4,1,0.0,0.0,0.0
10125,717406983,30,M,5281.0,8395,62,0.000,Attrited Customer,20.0,0,0.0,0.0,0.0
10126,714337233,43,F,10388.0,10294,61,0.189,Attrited Customer,18.1,1,0.0,0.0,0.0

In [11]:
customer360.to_csv(

'../data/customer360_enriched.csv',

index=False

)